add boilerplate
lucaventrice/todo_drf pull request #1
Opened 2020-11-25 12:33 UTC by lucaventrice

2020-11-26 14:19 UTC, mbaechtold requested changes

2020-11-26 14:19 UTC, mbaechtold commented on .vscode/settings.json
> +}
Bitte keine IDE spezifischen Konfigurationsdateien zum Repo hinzufügen. Lies dazu bitte https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/35750137/Globale+.gitignore-Datei

2020-11-26 14:19 UTC, mbaechtold commented on api/models.py
> +    return self.title
Bitte konfiguriere deine IDE so, dass sie automatisch einen Zeilenumbruch am Ende der Datei hinzufügt. Das ist auf GitHub erkennbar an dem roten Symbol.

2020-11-26 14:19 UTC, mbaechtold commented on api/urls.py
> +]
Bitte konfiguriere deine IDE so, dass sie automatisch einen Zeilenumbruch am Ende der Datei hinzufügt. Das ist auf GitHub erkennbar an dem roten Symbol.

2020-11-26 14:19 UTC, mbaechtold commented on api/views.py
> +    return JsonResponse("Api start point", safe=False)
Bitte konfiguriere deine IDE so, dass sie automatisch einen Zeilenumbruch am Ende der Datei hinzufügt. Das ist auf GitHub erkennbar an dem roten Symbol.

2020-11-26 14:43 UTC, mbaechtold requested changes

2020-11-26 14:43 UTC, mbaechtold commented on api/views.py
> +def apiOverview(request):
Wir verwenden für Klassen `class  CamelCase` und für Funktionen `def snake_case()`. Könntest du die Funktion bitte entsprechend umbenennen?

2020-11-26 16:27 UTC, mbaechtold requested changes

2020-11-26 16:27 UTC, mbaechtold commented on api/views.py
> +from django.shortcuts import render
Das importierte Modul wird nirgends verwendet. Bitte bring deiner IDE bei, dass sie dir solche Sachen sagt.

2020-11-26 16:27 UTC, mbaechtold commented on api/urls.py
> +	path('', views.apiOverview, name="api-overview"),
Hier ist ein Tab drin, anstatt vier Spaces. Meine IDE macht automatisch vier Leerschläge, wenn ich TAB drücke.

2020-11-27 15:52 UTC, lucaventrice commented on .vscode/settings.json
> +}
Ich habe .vscode im .gitignore aufgeführt.

2020-11-27 15:52 UTC, lucaventrice commented on api/models.py
> +    return self.title
Ich habe die Option 'Files: Insert Final Newline' aktiviert.

2020-11-27 15:53 UTC, lucaventrice commented on api/views.py
> +    return JsonResponse("Api start point", safe=False)
Ich habe die Option 'Files: Insert Final Newline' aktiviert.

2020-11-27 15:54 UTC, lucaventrice commented on api/views.py
> +from django.shortcuts import render
Die nicht verwendeten Module werden ausgegraut.

2020-11-27 15:54 UTC, lucaventrice commented on api/views.py
> +def apiOverview(request):
Ich habe die Funktion entsprechend umbenennt.

2020-11-27 15:54 UTC, lucaventrice commented on api/urls.py
> +]
Ich habe die Option 'Files: Insert Final Newline' aktiviert.

2020-11-27 16:00 UTC, lucaventrice commented on api/urls.py
> +	path('', views.apiOverview, name="api-overview"),
In den Settings ist "editor.tabSize": 4 eingestellt. Ich habe jetzt zusätzlich die Option "editor.detectIndentation" auf "false" gesetzt, da dies die Grundeinstellung von "tabSize 4" überschreiben kann. Ich nehme an, dass es ab jetzt stimmt.

2020-11-30 08:03 UTC, mbaechtold commented on .vscode/settings.json
> +}
Was spricht denn gegen ein globales .gitignore, wie im Artikel beschrieben?

2020-11-30 08:05 UTC, mbaechtold commented on .vscode/settings.json
> +}
Ausserdem müsstest du die Datei noch löschen, so dass sie in diesem PR nicht mitkommt.

2020-12-02 13:01 UTC, mbaechtold approved these changes
👍🏻

2020-12-02 13:46 UTC, merged