Add cud operations
lucaventrice/todo_drf pull request #13
Opened 2020-11-26 08:17 UTC by lucaventrice

2020-12-03 15:12 UTC, lucaventrice commented
@mbaechtold: Requesting review.

2020-12-03 16:48 UTC, mbaechtold requested changes

2020-12-03 16:48 UTC, mbaechtold commented on api/views.py
> +		'Update':'/task-update/<str:pk>/',
Hier sind Tabs anstatt Leerzeichen drin. Meine IDE zeigt mir das visuell an. GitHub leider nicht.

2020-12-03 16:48 UTC, mbaechtold commented on api/views.py
> +		'Delete':'/task-delete/<str:pk>/',
Hier sind Tabs anstatt Leerzeichen drin. Meine IDE zeigt mir das visuell an. GitHub leider nicht.

2020-12-04 07:49 UTC, lucaventrice commented on api/views.py
> +		'Update':'/task-update/<str:pk>/',
Ich habe nun im VSCode die Option "editor.renderWhitespace": "all" aktiviert und sehe somit immer, ob es sich um spaces oder tabs handelt.

2020-12-04 07:49 UTC, lucaventrice commented on api/views.py
> +		'Delete':'/task-delete/<str:pk>/',
Ich habe nun im VSCode die Option "editor.renderWhitespace": "all" aktiviert und sehe somit immer, ob es sich um spaces oder tabs handelt.

2020-12-04 08:00 UTC, mbaechtold approved these changes

2020-12-04 08:05 UTC, merged