add login form
lucaventrice/todo_drf pull request #43
Opened 2021-01-06 16:28 UTC by lucaventrice

I made a migration after creating the users app.

2021-01-07 08:01 UTC, mbaechtold requested changes
Könntest du bitte alle Änderungen, welche mit der `users` App zu tun haben, in einen eigenen Commit verschieben und in der Commit-Message beschreiben, warum diese Änderungen notwendig sind?

2021-01-07 14:08 UTC, lucaventrice commented
@mbaechtold requesting review: Ich habe unterdessen separate Commits erstellt und die Templates Struktur überarbeitet, damit ein erleichterter Ausbau weiterer HTML Seiten gewährleistet ist.

2021-01-07 14:49 UTC, mbaechtold commented on todo_drf/settings.py
> +STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
Inwiefern hängen diese zwei neuen Zeilen mit dem Commit zusammen? Gehört dies allenfalls zu einem anderen Commit?

2021-01-07 14:49 UTC, mbaechtold commented on todo_drf/settings.py
> +LOGOUT_URL = 'logout'
Inwiefern hängt die `LOGOUT_URL` mit diesem Pull Request zusammen, wo es um den Login geht?

2021-01-07 14:49 UTC, mbaechtold commented on api/migrations/0003_auto_20210106_1514.py
> +        migrations.AlterField(
Diese Migration hat nichts mit dem Feature zu tun, welches in diesem PR hinzukommt. Deshalb wäre es nützlich, wenn du in der Commit Message noch erklären würdest, warum du die Migration hinzugefügt hast.

2021-01-20 09:57 UTC, lucaventrice commented on todo_drf/settings.py
> +STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
Wird nicht benötigt, deshalb habe ich diesen Ausschnitt entfernt.

2021-01-20 09:57 UTC, lucaventrice commented on todo_drf/settings.py
> +LOGOUT_URL = 'logout'
Wird nicht benötigt, deshalb habe ich 'logout' entfernt.

2021-01-20 10:34 UTC, lucaventrice commented on api/migrations/0003_auto_20210106_1514.py
> +        migrations.AlterField(
Die Commit Message geht jetzt neu spezifischer auf die Abhängigkeit zum vorherigen PR ein.

2021-01-20 13:33 UTC, lucaventrice commented
Bei den neuen commits von heute habe ich fälschlicherweise den code sortiert, was zu einem grösseren Diff führt.

2021-01-20 17:10 UTC, lucaventrice commented
Habe versucht die Codeformatierung rückgängig zu machen. @mbaechtold requesting review.

2021-01-29 09:31 UTC, mbaechtold requested changes

2021-01-29 09:31 UTC, mbaechtold commented on api/migrations/0002_task_user.py
> +            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
Bitte rückgängig machen durch Löschen des Commits.

2021-01-29 10:10 UTC, lucaventrice commented on api/migrations/0002_task_user.py
> +            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
Der Commit ist gelöscht

2021-01-29 13:31 UTC, lucaventrice commented
I removed unnecessary CSS in login.html. @mbaechtold requesting review.

2021-01-29 13:32 UTC, mbaechtold commented on api/migrations/0002_task_user.py
> +            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
👍🏻

2021-01-29 13:32 UTC, mbaechtold approved these changes
👍🏻 Und ab die Post...

2021-01-29 13:34 UTC, merged