formatting imports with isort and 4tw config
lucaventrice/todo_drf pull request #46
Opened 2021-01-07 16:05 UTC by lucaventrice

2021-01-07 16:51 UTC, mbaechtold requested changes

2021-01-07 16:51 UTC, mbaechtold commented on pyproject.toml
> +'''
Dies ist die Konfiguration für `black`. Das hat mit diesem Pull Requests nichts zu tun.

2021-01-20 09:46 UTC, lucaventrice commented on pyproject.toml
> +'''
Habe `black` aus dem toml entfernt.

2021-01-20 11:16 UTC, mbaechtold requested changes
Mir scheint, als ob jetzt auch schon `black` über den Code gelaufen ist. Kannst du das bitte rückgängig machen? Es geht hier nur um die Sortierung der Importe.

2021-01-20 15:58 UTC, lucaventrice commented
Ok, habe Black im VsCode entfernt und die Änderungen rückgängig gemacht.

2021-01-21 07:43 UTC, mbaechtold requested changes
Kannst du bitte noch die Konfiguration für `isort` erstellen? Die war bei einem früheren Commit noch vorhanden...

2021-01-22 17:08 UTC, lucaventrice commented
> Kannst du bitte noch die Konfiguration für `isort` erstellen? Die war bei einem früheren Commit noch vorhanden...

It's done! 😃 @mbaechtold requesting review.

2021-01-24 16:32 UTC, mbaechtold approved these changes
👍🏻

2021-01-27 16:31 UTC, merged