setup and run flake8, changes made according to error messages
lucaventrice/todo_drf pull request #47
Opened 2021-01-20 15:02 UTC by lucaventrice

2021-01-27 16:46 UTC, mbaechtold requested changes
@lucaventrice, kannst du bitte auf den neuesten Stand vom `main` branch rebasieren?

2021-01-27 16:55 UTC, mbaechtold requested changes
Auch hier scheint es so, als ob "black" schon seinen Dienst verrichtet hat (`"` anstatt `'`), oder? Ich denke nicht, dass "flake8" vorgibt, welches Zeichen für die Begrenzung von Zeichenketten verwendet werden soll. Kannst du das bitte rückgängig machen?

2021-01-28 08:46 UTC, lucaventrice commented
@mbaechtold requesting review.

2021-01-28 09:09 UTC, mbaechtold approved these changes
👍🏻 Feel free to merge!

2021-01-28 09:09 UTC, mbaechtold commented on api/views.py
> +        return Response({'response': 'You don't have permission to delete that.'})
Diese Änderung hat nichts mit `flake8` zu tun. Du musst es aber nicht anpassen.

2021-01-28 09:09 UTC, mbaechtold commented on api/views.py
> +    return Response('Task deleted!')
Diese Änderung hat nichts mit `flake8` zu tun. Du musst es aber nicht anpassen.

2021-01-28 15:36 UTC, merged

2021-01-29 07:38 UTC, mbaechtold commented on api/views.py
> +        return Response({'response': 'You don't have permission to delete that.'})
Ah, du hättest das doch noch anpassen müssen :-) Das gibt ja Syntaxfehler.

2021-01-29 10:11 UTC, lucaventrice commented on api/views.py
> +        return Response({'response': 'You don't have permission to delete that.'})
Hoppla...