password reset
lucaventrice/todo_drf pull request #53
Opened 2021-02-05 08:58 UTC by lucaventrice

custom password reset forms
password reset link in login page
local file based email backend server

2021-02-05 15:10 UTC, mbaechtold requested changes
Bitte noch rebasieren, vielleicht ein paar Kommentare umsetzen und dann ab die Post...

2021-02-05 15:10 UTC, mbaechtold commented on todo_drf/settings.py
> +EMAIL_FILE_PATH = str(BASE_DIR.joinpath('sent_emails'))
Dies funktioniert sicher ohne weiteres. Da `BASE_DIR` aber ein `Path()`Objekt ist, könnte man so etwas machen:

```
EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'
```

Du musst es aber nicht anpassen...

Ist die explizite Umwandlung nach `str` nötig?

2021-02-05 15:10 UTC, mbaechtold commented on users/templates/users/password_reset_confirm.html
> +                {% endfor %}
Für die Lesbarkeit des Codes würden hier noch ein paar Einrückungen nützlich sein. Die verschachtelte Schleife ist nicht so einfach zu lesen momentan.

2021-02-05 15:10 UTC, mbaechtold commented on users/templates/users/password_reset_done.html
> +    If the given email is registered a message has been sent with instructions to reset your password.
Find ich gut. So kann man nicht herausfinden, ob es für eine bestimmte E-Mail-Adresse einen Benutzeraccount hat. Wie war das eigentlich bei der Registration gelöst? 🤔

2021-02-11 15:29 UTC, lucaventrice commented on todo_drf/settings.py
> +EMAIL_FILE_PATH = str(BASE_DIR.joinpath('sent_emails'))
Merci für das Feedback, ich habe es so angepasst.

2021-02-11 15:33 UTC, lucaventrice commented on users/templates/users/password_reset_confirm.html
> +                {% endfor %}
Die Einrückungen wurden angepasst.

2021-02-11 15:40 UTC, lucaventrice commented on users/templates/users/password_reset_done.html
> +    If the given email is registered a message has been sent with instructions to reset your password.
Ich habs getestet und herausgefunden, dass im Moment ein neuer Account mit der gleichen E-Mail Adresse erstellt werden kann.

2021-02-12 08:43 UTC, mbaechtold requested changes
Danke für die Nachbesserungen. Könntest du bitte noch rebasieren?

2021-02-17 09:39 UTC, lucaventrice commented
Diese Branch ist nun auf main rebasiert. Requesting review @mbaechtold.

2021-02-17 10:01 UTC, mbaechtold reviewed
Was passiert nun, wenn es mehrere Benutzeraccounts gibt, bei welchen die gleiche E-Mail-Adresse hinterlegt ist? Für welchen Account wird dann der Passwort-Reset durchgeführt?

2021-02-24 07:19 UTC, mbaechtold commented
Wir fahren hier weiter, sobald wir das Custom User Model haben.

2021-03-04 14:32 UTC, mbaechtold approved these changes

2021-03-04 14:32 UTC, merged